### ISSUE TITLE
Website for the gem is not working

### ISSUE THREAD

**Issue by Mingan** [piotrmurach/finite_machine#48]
The [website](http://peter-murach.github.io/finite_machine/) linkes from [RubyGems](https://rubygems.org/gems/finite_machine) as `Homepage` does not exist.

**Comment by piotrmurach** [comment]
Hi, recently I have changed my GitHub handle to `piotrmurach` which caused few issues :) I have fixed majority of references, however the rubygems homepage link is only editable through new library release which I haven't done yet but fixed in [master](https://github.com/piotrmurach/finite_machine/blob/master/finite_machine.gemspec#L13). So to access website please go [here](http://piotrmurach.github.io/finite_machine/).
