### ISSUE TITLE
Terminal state

### ISSUE THREAD

**Issue by mits87** [piotrmurach/finite_machine#49]
Hi,

I have a little problem because I would like read terminated state but I can't If:

`terminal [:failed, :finished]`

1. I don't see any callback for terminated

```
state_machine.on_terminated do |event|
...
end
```

2. If I have few states of terminal then method **terminated?** is always false. In my opinion if one of states is in terminal array then should be true. What are you thinking about it?

Thanks
Peter

**Comment by piotrmurach** [comment]
Hi, thanks for using the library.

Terminal state is not different from any other state therefore you should be able to use standard callbacks:
```ruby
state_machine.on_enter :failed do |event|
...
end
```
Currently the `terminal` allows to specify only a single terminal state. Expanding this to include more than one terminal state is a good idea.

**Comment by mits87** [comment]
Thank you for your answer. 
It would be great if the `terminal` could take more states than one.

PS. Is it possible do something like this:

```
state_machine.on_enter(:failed, :finished) do |event|
...
end
```
?

Because I didn't find anywhere this case.

**Comment by piotrmurach** [comment]
I agree it would be great. Currently there are few quite important issues to address first.

The callbacks currently work with single state names due to dynamic method definitions. However, the underlying code accepts any number of arguments so I would just test if your callback gets fired for two different states.

Unfortunately I'm without internet now and my provider is less than helpful restoring it so may be unavailable for couple days.

**Comment by piotrmurach** [comment]
This was actually always implemented, the `terminal` expects comma delimited symbols:

```ruby
terminal :failed, :finished
```

I've updated [docs](https://github.com/piotrmurach/finite_machine#13-terminal) to explain multiple terminal states.
