### ISSUE TITLE
Unable to define constructors on custom classes

### ISSUE THREAD

**Issue by RoseAndres** [piotrmurach/finite_machine#69]
### Describe the problem
I'm trying to extend the FiniteMachine::Definition class and am unable to define my own constructor (`#initialize`). The `#new` method is directly overridden in `definition.rb` and its superclass in `state_machine.rb`, which prevents developers from creating their own constructors on classes extending either FiniteMachine::Definition or FiniteMachine.

### Steps to reproduce the problem
```
class StateManager < FiniteMachine::Definition
  attr_accessor :state_attr

  def initialize(*args)
    @state_attr = args[0]
  end
end

# trying to initialize the class above by calling `StateManager.new(:some_attr)` will invoke 
# FiniteMachine::Definition's implementation of `#new`, short-circuiting any `initialize` method 
# created on the custom class
```

### Actual behaviour
Custom classes are unable to define their own `#initialize` method (constructor) on classes extending classes from the FiniteMachine gem.

### Expected behaviour
Custom classes should be able to define their own `#initialize` method (constructor) on classes extending classes from the FiniteMachine gem.

### Describe your environment

* OS version: macOS Big Sur 11.1
* Ruby version: 3.0.0p0
* FiniteMachine version: 0.14.0

**Comment by piotrmurach** [comment]
Hi there 👋 

Thanks for using `finite_machine` gem.

This is by design. Similar to `FiniteMachine.define`, the `FiniteMachine::Definition` is meant to describe the state machine and nothing else. There is no reason to have initialization with custom state attributes as they wouldn't be a way to use them in state machine definition anyhow. The way I like to think of `FiniteMachine::Defintion` is a template for creating state machines instances. Each instance can then be targetted by different objects in separate threads etc. So following from this, you would first create your definition:

```ruby
class CustomMachine < FiniteMachine::Definition
  # express all states and their possible transitions
end
```

And then integrate it with your code however you like it, for example, this way:

```ruby
class StateManager
  attr_accessor :state_attr

  def initialize(*args)
    @state_attr = args[0]
    @machine = CustomMachine.new(self)
    @machine.restore!(@state_attr)  # set machine to desired state
  end

  # other methods which trigger transitions
  def move
    @machine.move
  end
end
```

**Comment by RoseAndres** [comment]
Hi there, thanks for your quick response 🙂 

The initialize stuff is more of a side-effect of something else I'm trying to do, one could say. It's harder to explain without dropping all of my code, but I'm essentially trying to add the following:

```
class StateManager < FiniteMachine::Definition
  # all states and transitions

  on_enter do |event|
    target.notify_state_change(instance_variable_get(:@state_attr), event.to)
  end
end

class SomeModelClass < ActiveRecord::Base
  def notify_state_change(state_attr, new_value)
    public_send("#{state_attr}=", new_value)
  end
end
```

**Comment by RoseAndres** [comment]
While I was unable to accomplish my goal with the above behavior, I was able to figure it out 🙂 

Thanks for your help!

**Comment by piotrmurach** [comment]
Glad you get to resolve your problem. The design of this gem 'forces' a certain separation between the state machine and other objects acting on it. The communication happens via triggers and callbacks. You should be able to pass any information this way. That's why there is no built-in integration for ActiveRecord or any other ORM. You're left to decide how you want to store your state. In future, you may move to a different data storage model, another framework which shouldn't affect the state machine. If you want to ensure maintenance, then this gem should continue to work even for Rails 10. 

The `FiniteMachine::Definition` could potentially be made into a module but that would possibly make the boundaries even more blurry and let a class grow in complexity. It's a balancing act, and there are always compromises.

Thanks for using `finite_machine` and hope it helps you build whatever you're working on.
